"""
Django settings for myrecipes project.

Generated by 'django-admin startproject' using Django 5.1.6.
For more information: https://docs.djangoproject.com/en/5.1/topics/settings/
Full list of settings: https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

from django.conf.global_settings import LOGIN_REDIRECT_URL

# Базовая директория проекта (автоматически определяется как папка, где находится этот файл)
BASE_DIR = Path(__file__).resolve().parent.parent

# Секретный ключ для безопасности приложения
# ВАЖНО: Для продакшена замените на уникальный ключ, сгенерированный через get_random_secret_key()
SECRET_KEY = 'django-insecure-@6mu^sd$&%8j@v8n(ey007#wq7ry80^&4sv=-$$2(f+9sk3l6d'  # Предупреждение: небезопасно для продакшена

# Режим отладки: True для разработки, False для продакшена
DEBUG = True  # Измените на False при развертывании на сервере

# Разрешённые хосты: указывает, с каких доменов можно обращаться к сайту
ALLOWED_HOSTS = ['localhost', '127.0.0.1']  # Добавьте свой домен в продакшене, например, 'yourdomain.com'

# Установленные приложения Django и вашего проекта
INSTALLED_APPS = [
    'django.contrib.admin',        # Админ-панель
    'django.contrib.auth',         # Аутентификация пользователей
    'django.contrib.contenttypes', # Система типов контента
    'django.contrib.sessions',     # Управление сессиями
    'django.contrib.messages',     # Система сообщений для пользователя
    'django.contrib.staticfiles',  # Обработка статических файлов (CSS, JS, изображения)
    'recipes',                     # Ваше приложение "recipes"
]

# Промежуточное ПО (middleware) для обработки запросов и ответов
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',         # Защита безопасности
    'django.contrib.sessions.middleware.SessionMiddleware',  # Управление сессиями
    'django.middleware.common.CommonMiddleware',            # Общие функции (например, обработка заголовков)
    'django.middleware.csrf.CsrfViewMiddleware',            # Защита от CSRF-атак
    'django.contrib.auth.middleware.AuthenticationMiddleware', # Поддержка аутентификации
    'django.contrib.messages.middleware.MessageMiddleware',   # Поддержка сообщений
    'django.middleware.clickjacking.XFrameOptionsMiddleware', # Защита от кликджекинга
]

# Главный файл маршрутизации URL
ROOT_URLCONF = 'myrecipes.urls'

# Настройки шаблонов
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates', # Используем стандартный шаблонизатор Django
        'DIRS': [BASE_DIR / 'templates'],  # Добавлена папка templates в корне проекта для общих шаблонов
        'APP_DIRS': True,                  # Автоматический поиск шаблонов в папках приложений
        'OPTIONS': {
            'context_processors': [        # Процессоры контекста добавляют данные в каждый шаблон
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Приложение WSGI для работы с веб-сервером
WSGI_APPLICATION = 'myrecipes.wsgi.application'

# Настройки базы данных (SQLite для разработки)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',  # Путь к файлу базы данных
    }
}

# Валидаторы паролей для безопасности
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Настройки интернационализации
LANGUAGE_CODE = 'ru-ru'  # Изменено на русский язык
TIME_ZONE = 'UTC'        # Часовой пояс (можно изменить, например, на 'Europe/Moscow')
USE_I18N = True          # Поддержка перевода
USE_TZ = True            # Поддержка часовых поясов

# Настройки статических файлов (CSS, JS, изображения)
STATIC_URL = '/static/'           # URL для доступа к статическим файлам
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Папка для сбора статических файлов в продакшене
STATICFILES_DIRS = [BASE_DIR / "static"]  # Дополнительная папка для статических файлов

# Настройки медиафайлов (загружаемые пользователем файлы, например, изображения рецептов)
MEDIA_URL = '/media/'           # URL для доступа к медиафайлам
MEDIA_ROOT = BASE_DIR / 'media' # Папка для хранения медиафайлов

# Тип первичного ключа по умолчанию
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = 'recipe_list'